modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/coins/issues"

[[mods]]
modId="coins"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.coins]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.coins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.coins]]
    modId="bookshelf"
    mandatory=true
    versionRange="[4.4.74,)"
    ordering="AFTER"
    side="BOTH"
